# Template of Cloudformation GameLift Matchmaker
# usage:
# LMatchmakingGameMode001:
#   Type: AWS::CloudFormation::Stack
#   Properties:
#     TemplateURL: !Join ['',['https://',!Ref BackendName,'buildbucket.s3.amazonaws.com/cloudformation_matchmaker.yaml']]
#     Parameters:
#       MatchmakerName: !Join ['',[!Ref Prefix,!Ref BackendName,'matchmaking-gm001']]
#       QueueArn: !GetAtt LGameQueue.Arn
#       RuleSetName: !Ref LMatchmakingRuleSet
#       RequirePlayerAcknowledge: false
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MatchmakerName:
    Type: String
    Default: matchmakername
  RuleSetName:
    Type: String
    Default: rulesetname
  QueueArn:
    Type: String
    Default: default
  RequirePlayerAcknowledge:
    Type: Boolean
    Default: false
Resources:
  LMatchmakingConfiguration:
    Type: 'AWS::GameLift::MatchmakingConfiguration'
    Properties:
      Name: !Ref MatchmakerName
      Description: !Join ['',[ !Ref MatchmakerName ,' Matchmaker Configuration']]
      AcceptanceRequired: !Ref RequirePlayerAcknowledge
      AdditionalPlayerCount: 0
      BackfillMode: MANUAL
      GameSessionData: !Ref MatchmakerName
      GameSessionQueueArns:
        - !Ref QueueArn
      RequestTimeoutSeconds: 20
      RuleSetName: !Ref RuleSetName