# Template of CloudFormation Functions
# usage: https://TODO:
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Prefix:
    Type: String
  Gateway: 
    Type: String
  BackendBucket:
    Type: String
  FunctionName:
    Type: String
  FunctionBuild:
    Type: String
  FunctionHandler:
    Type: String
  FunctionIAMArn:
    Type: String
  FunctionSecurityGroupIds:
    Type: CommaDelimitedList
  FunctionSubnetIds:
    Type: CommaDelimitedList
  VpcLinkId:
    Type: String
Resources:
  LFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Join ['',[!Ref Prefix,!Ref FunctionName]]
      Handler: !Ref FunctionHandler
      Runtime: go1.x
      Timeout: 30
      MemorySize: 128
      Role: !Ref FunctionIAMArn
      Code:
        S3Bucket: !Ref BackendBucket
        S3Key: !Ref FunctionBuild
      VpcConfig:
        SecurityGroupIds: !Ref FunctionSecurityGroupIds
        SubnetIds: !Ref FunctionSubnetIds
  LFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - LFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join ['',[!Ref Prefix,!Ref FunctionName]]
      Principal: apigateway.amazonaws.com
      SourceArn: !Join ['',['arn:aws:execute-api:',!Ref AWS::Region,':',!Ref AWS::AccountId,':',!Ref Gateway,'/*/*/',!Ref Prefix,!Ref FunctionName]]
  LApi:
    Type: AWS::ApiGatewayV2::Integration
    DependsOn:
      - LFunction
    Properties:
      ApiId: !Ref Gateway
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      IntegrationUri: !Join ['',['arn:aws:apigateway:',!Ref AWS::Region,':lambda:path/2015-03-31/functions/',!GetAtt LFunction.Arn,'/invocations']]
      ConnectionType: INTERNET
      PayloadFormatVersion: 1.0
  LRoute:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - LApi
    Properties:
      ApiId: !Ref Gateway
      RouteKey: !Join ['',['ANY /',!Ref Prefix,!Ref FunctionName]]
      AuthorizationType: NONE
      Target: !Join ['',['integrations/',!Ref LApi]]